#!/usr/bin/env python

import sys

def options(opt):
        opt.load('compiler_cxx')

def configure(conf):
        conf.load('compiler_cxx')


def build(bld):
    bld.program(
        source       = 'example.cpp',
        target       = 'example',
        includes     = ['.', '/usr/include', '/usr/local/include'],
        cxxflags     = ['-O3', '-Wall', '-m32'],
        lib          = ['m'],
        linkflags    = ['-m32'],
        framework   = ['IScore'],
        libpath      = ['/usr/lib', '/usr/local/lib', '.'],
    )

